### ISSUE TITLE
Android Marshmallow Support?

### ISSUE THREAD

**Issue by jamesmontemagno** [aritchie/biometrics#2]
I am thinking we could swap out the samsung stuff for the official stuff? Thoughts?

**Comment by seligam** [comment]
not swap, but add it as preferred way on 6.0+ devices
and keep samsung support for older android version

On 19. 11. 2015 23:10, James Montemagno wrote:

I am thinking we could swap out the samsung stuff for the official stuff? Thoughts?

—
Reply to this email directly or view it on GitHub<https://github.com/aritchie/biometrics/issues/2>.

****************************************************************************** This email and any files transmitted with it are confidential and may be subject to copyright. They are intended solely for the use of the individual or entity to which they are addressed. If you have received this message in error please notify AFS immediately by return email. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of AFS, except where an authorized sender specifically states them to be the views of AFS. It is your responsibility to verify this email and any attachments for the presence of viruses. AFS accepts no liability for any damage caused by any virus transmitted. []

**Comment by aritchie** [comment]
Can't swap out because galaxy S3 is handcuffed to android 5 and has a fingerprint sensor.  Should be easy enough...

**Comment by aritchie** [comment]
I finally added support for marshmallow in very betaish form.  I have an old samsung to test its fingerprint sensor, but not a new nexus.  It looks as though the new droid emulator has fingerprint testing support of some kind. 

In the meantime, if I could get some more eyes on this, it would be appreciated.

**Comment by djdmbrwsk** [comment]
`MarshmallowBiometricsImpl.cs` is looking great!  Watch out inheriting from `FingerprintManager.AuthenticationCallback`.  Users will get a class not found exception they're not on Marshmallow.

**Comment by tonyignat** [comment]
I am using Marshmellow not sure what I am missing but always the sensor check returns false, my manifest has required permissions, the sample works fine but my PCL project is not working. Do I need to add anything else in code of android project to make this work. Thanks in advance.

**Comment by aritchie** [comment]
The full implementation for M was never finished.

**Comment by tonyignat** [comment]
I had already built my whole app in M, now to implement fingerprint, what do  I need to do ? Any suggestions pls. Yet, the sample one works fine in the mobile.

**Comment by djdmbrwsk** [comment]
@tonyignat checkout [FingerprintManager](https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager.html).  Specifically the [Authenticate()](https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager.html#authenticate(android.hardware.fingerprint.FingerprintManager.CryptoObject, android.os.CancellationSignal, int, android.hardware.fingerprint.FingerprintManager.AuthenticationCallback, android.os.Handler)) method.

**Comment by aritchie** [comment]
@tonyignat this project should work fine for samsung devices, but I never was able to test/finish it for M (Nexus devices, etc).  If the example project is working fine for your cases, make sure you follow the instructions for the permissions on the readme of this project

**Comment by djdmbrwsk** [comment]
@aritchie I noticed recently that Samsung devices that were updated to M now use the Android API. Not sure if those devices continue to support the original Samsung API or not, I would guess yes, but I haven't tested.

**Comment by tonyignat** [comment]
I used Moto G4. Now am trying in my AVD. Yet now it shows that "System.ArgumentException: No platform plugin found.  Did you install the nuget package in your app project as well?" AM sure that I have referenced it in all my projects. Does this issue seems familiar to you guys...? I know that I am missing something small but not sure what ?

**Comment by aritchie** [comment]
Yes - this means you didn't install the nuget package in your main android/ios projects.

**Comment by tonyignat** [comment]
This is the strangest part , I have installed the reference in all my projects.

**Comment by subbuxamarin** [comment]
Hi,

I am using Biometric.Instance for Tocuh Id authentication. Once i logout app the biometric instance still exists and not asking for thumb next time. I would like to clear Biometric instance on logout, apparently there is no method or property to do that. Can any one help me how to clear biometric instance.

Thanks in advance

Subbu

**Comment by aritchie** [comment]
This library is no longer supported. Please use [https://www.nuget.org/packages/Plugin.Fingerprint/](Plugin.Fingerprint)
